# Generated by Django 5.0.8 on 2025-02-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_transaction_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='bank.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
